language: java

jdk: oraclejdk8

sudo: true

dist: trusty

services:
  - mysql

install: true

sckript: ./mvnw test -B

build: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

env:
  - CABARE_LOGIN=root CABARE_PASSWORD=
